// FileSystemComServer.idl : IDL source for FileSystemComServer
//

// This file will be processed by the MIDL tool to
// produce the type library (FileSystemComServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(A9DCCC9E-5B5A-4E23-B726-259F223816AE),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IFileManagerCom : IDispatch{
	[id(1)] HRESULT GetFolder(BSTR path, VARIANT * names);
	[id(2)] HRESULT GetRoot(VARIANT * names);
	[id(3)] HRESULT GetListIcon([out] VARIANT * icons);
	[id(4)] HRESULT OpenItem([in] BSTR path, [out] BOOL * isFolder);
	[id(5)] HRESULT DeleteItem([in] BSTR path);
	[id(6)] HRESULT CopyItem([in] const BSTR newPath, [in] const BSTR oldPath);
	[id(7)] HRESULT MoveItem([in] const BSTR newPath, [in] const BSTR oldPath);
	[id(8)] HRESULT RenameItem([in] const BSTR newPath, [in] const BSTR oldPath);
};
 
[
	uuid(052A1B68-7229-4196-8612-441AEF1683F0)
]
struct DataItem
{
	BSTR name;
	BOOL isFolder;
	//image
	UINT id;
	UINT idOpen;
	BOOL haveSubFolder;
};

[
	uuid(76333070-6F9C-416C-B18F-CDEFDFE5242D),
	version(1.0),
]
library FileSystemComServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(0FC9B050-6CD8-410E-A012-47EAAF58ADF7)
	]
	coclass FileManagerCom
	{
		[default] interface IFileManagerCom;
	};

	struct DataItem;
};

